# Generated by Django 4.2.23 on 2025-07-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=50)),
                ('etag', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('channel_id', models.CharField(max_length=100)),
                ('resource_channel_id', models.CharField(max_length=100)),
                ('thumbnails', models.JSONField()),
            ],
            options={
                'unique_together': {('channel_id', 'resource_channel_id')},
            },
        ),
    ]
