# Generated by Django 4.2.23 on 2025-07-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
