# Generated by Django 4.2.23 on 2025-07-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0002_subscription_is_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100)),
                ('video_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('published_at', models.DateTimeField()),
                ('is_watched', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='fetcher.subscription')),
            ],
        ),
    ]
