# Generated by Django 4.2.23 on 2025-07-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='snippet',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
