# Generated by Django 4.2.23 on 2025-07-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0004_video_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_rewatchable',
            field=models.BooleanField(default=False),
        ),
    ]
